CREATE TABLE Person
(
ID NUMBER(5), 
Name VARCHAR2(30)
);
ALTER TABLE PERSON ADD HP VARCHAR2(20);
ALTER TABLE PERSON DROP COLUMN TEL;
ALTER TABLE PERSON RENAME  COLUMN HP TO TEL;
ALTER TABLE PERSON MODIFY TEL VARCHAR2(13);
ALTER TABLE PERSON DROP COLUMN TEL;
